int types (Stmt* s);
    // "invalid `\\´ : unexpected pointer type"
    // "invalid `\\´ : expected pointer type"
    // "invalid `.´ : expected tuple type"
    // "invalid `.´ : index is out of range"
    // "invalid `.´ : expected user type"
    // "invalid `.´ : expected user type"
    // "invalid call to \"%s\" : type mismatch"
    // "invalid constructor \"%s\"
    // "invalid assignment to \"%s\" : type mismatch"
    // "invalid return : type mismatch"
    // "invalid assignment to \"%s\" : type mismatch"
    // "invalid assignment : type mismatch"
    // "invalid condition : type mismatch"
